server:
  port: 8888

#数据库连接
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://180.76.169.35:3306/SecKill?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: azusa520
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      max-active: 1000
      initial-size: 100
      max-wait: 60000
      min-idle: 500
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      filters: stat
      max-pool-prepared-statement-per-connection-size: 20
      use-global-data-source-stat: true
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500

  thymeleaf:
    cache: false
    enabled: true
    encoding: UTF-8
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html
    servlet:
      content-type: text/html
  redis:
    host: 180.76.169.35
    port: 6379
    timeout: 30
    password:
    jedis:
      pool:
        max-active: 1000
        max-idle: 500
        max-wait: 500

  resources:
    add-mappings: true
    cache:
      period: 3600
    chain:
      cache: true
      enabled: true
      compressed: true
      html-application-cache: true
    static-locations: classpath:/static/

  rabbitmq:
    host: 180.76.169.35
    port: 5672
    username: admin
    password: admin
    virtual-host: /
    listener:
      simple:
        concurrency: 10
        max-concurrency: 10
        prefetch: 1
        auto-startup: true
        default-requeue-rejected: true
    template:
      retry:
        initial-interval: 1000
        max-attempts: 3
        max-interval: 1000
        multiplier: 1

mybatis-plus:
  configuration:
    default-enum-type-handler: org.apache.ibatis.type.EnumTypeHandler
    map-underscore-to-camel-case: true
    default-executor-type: simple
    jdbc-type-for-null: null
  global-config:
    banner: off
  type-aliases-package: cn.hfbin.seckill.entity
  mapper-locations: classpath:mybatis/mappers/*.xml
